### ISSUE TITLE
Famille

### ISSUE THREAD

**Issue by sepia81** [Paxatagore/wall#12]
faire en sorte que la carte du monde sur laquelle apparissent tous les membres de la famille (pas seulement les participants) se constitue automatiquement à partir des adresses renseignées dans les comptes de chacun.

Je dois pouvoir renseigner moi-même directement sur le serveur les adresses de certains, ce peut-être un début.

**Comment by Paxatagore** [comment]
je crée la branche "carteMondiale" pour travailler là dessus.

**Comment by Paxatagore** [comment]
Il faudrait qu'un certain nombre de gens mettent leurs adresses.

**Comment by sepia81** [comment]
ok. si tu veux, je peux mettre quelques adresses (vagues) directement sur le serveur cet après-midi.
