### ISSUE TITLE
Site

### ISSUE THREAD

**Issue by sepia81** [Paxatagore/wall#15]
Ajouter quelque part sur le site la liste des personnes inscrites. Histoire que chacun sache qui reçoit les messages qu'il envoie, a accès aux photos, etc... 

L'ajouter dans la rubrique "famille" ? 
L'ajouter en page d'accueil dans une colonne à côté des messages ? (bof)
Créer carrément une nouvelle rubrique : "le site" (qui pourrait comprendre deux "articles" : "mon compte" et "liste des inscrits au site")

**Comment by Paxatagore** [comment]
Je vois ça dans une optique globale, avec un who's who (pour faire plaisir à Christian), chacun ayant sa propre page.

**Comment by sepia81** [comment]
Moui, sans doute, mais j'ai peur que cela soit trop sophistiqué pour certains, et que cela te demande bcp de temps sans qu'on soit certain que les gens y trouveront une véritable utilité.

**Comment by Paxatagore** [comment]
Fait.
