### ISSUE TITLE
Architecture du site

### ISSUE THREAD

**Issue by sepia81** [Paxatagore/wall#27]
Limiter le nombre de rubriques principales (celles qui apparaissent en haut de chaque page du site) mais faire apparaître un menu déroulant contenant les subdivisions pour chaque rubriques : 
- Mur
- Famille
  . arbre généalogique
  . répartition géographique
- Photos
  . album X
  . album Y
- Cousinade 2015
  . les souvenirs
  . les participants
  . les informations pratiques
- Site E&G
  . liste des membres du site (avec les mails)
  . mon compte

**Comment by Paxatagore** [comment]
Fait (sauf pour les photos).
