### ISSUE TITLE
les 2 sites - dates de naissance

### ISSUE THREAD

**Issue by sepia81** [Paxatagore/wall#43]
lorsque quelqu'un indique sa date de naissance, ça sert à quoi ? 
- est-ce que ça pourrait apparaître dans la liste des membres du site ? 
- éventuellement, si on insère un calendrier sur le site, on peut imaginer que la date de naissance s'y insère automatiquement (comme un adresse s'insère sur la carte du monde)

**Comment by Paxatagore** [comment]
Point 1 fait sur le site G&M.

**Comment by Paxatagore** [comment]
Point 1 fait sur le site E&G.
