### ISSUE TITLE
déménagement des photos

### ISSUE THREAD

**Issue by sepia81** [Paxatagore/wall#54]
Il y a deux albums qu'il faudrait supprimer : ce sont les 2 qui n'ont pas de numéro : 
- 1980-2010 : branche anne-marie
- 1980-2010 : branche Elie

Mais ils contiennent des photos : 
- les 2 photos de l'album "1980-2010 : branche anne-marie" devraient être déplacées, avec leurs commentaires, **dans l'album 08**
- les 2 photos de l'album "1980-2010 : branche Elie" **dans l'album 02**

En outre, il faudrait déplacer : 
- les photos "photos Madeleine009" et "photos Madeleine004" de l'album 02 **vers l'album 01**
- la photo "photos Madeleine1" de l'album 04 **vers l'album 02**
- les photos "Ostricourt 1929- autour de la table" et "Ostricourt 1929- autour de la table 2" et "Ostricourt 1929- sur le balcon" de l'album 01 **vers l'album 08**

**Comment by Paxatagore** [comment]
La fonction de déplacement de photos est opérationnelle.

**Comment by Paxatagore** [comment]
Les photos ont été déplacées. ça marche très bien.
